# Generated by Django 6.0.3 on 2026-03-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
