# Generated by Django 6.0.3 on 2026-03-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_orderitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_products',
            new_name='featured_product',
        ),
    ]
